# Generated by Django 3.2.18 on 2023-06-04 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('division', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=1000)),
                ('present_address', models.CharField(max_length=1000)),
                ('about', models.CharField(max_length=1000)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('personal_number', models.IntegerField()),
                ('relative_number', models.IntegerField()),
                ('emergency_number', models.IntegerField()),
                ('nid_number', models.IntegerField()),
                ('person_face_image', models.ImageField(upload_to='person_face_image')),
                ('person_nid_image', models.ImageField(upload_to='person_nid_image')),
                ('person_fingerprint_image', models.ImageField(upload_to='person_fingerprint_image')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2023, 6, 4, 7, 3, 44, 129086))),
            ],
        ),
    ]
